apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml  # <--- This must match your file name!
configMapGenerator:
- name: app-config
  literals:
  - message="Welcome to the Base App"
